################################################################################
# R PACKAGE:   mframe
# FILE:        R/build.R
# DESCRIPTION: Utility script & instructions to build the R package
#              for submission to CRAN
# AUTHOR:      Enrique Bengoechea <enrique.bengoechea@credit-suisse.com>
# CREATED ON:  10/06/2009
# LICENSE:     GPL-2
################################################################################

# 0) Check all unit tests pass on a fresh install:
library(DevTools);
devPath(file.path("C:", "ebe", "Work", "Projects", "PaRiS_R", "mframe"));
ut()

# 1) Clear documentation produced in previous runs 
unlink(file.path(devPath(), "man", "*"))
unlink(file.path(devPath(), "chm", "*"))

# 2) Run Roxygen on the project (normally through StatET):
roxygen()

# 3) Remove Rd files generated by Roxygen that are not desired (doc files 
#    of objects that are documented together with other objects):

toRm <- c(
	"metadata.default", "metadata.mframe", 
    "metadataReplace", "metadataReplace.mframe",
    
	"key.default", "key.dfMetadata", "key.mframe",  
	"keyReplace", "keyReplace.default", "keyReplace.dfMetadata",
		"keyReplace.mframe",
		
	"keys.default", "keys.dfMetadata", "keys.mframe",  
	"keysReplace", "keysReplace.default", "keysReplace.dfMetadata",
		"keysReplace.mframe",
		
	"paramsReplace", "params.default", "params.dfMetadata", 
		"params.mframe",
		
	"varType.default", "varType.varMetadata", 
		"varType.dfMetadata", "varType.mframe", 
    "varTypeReplace", "varTypeReplace.default", "varTypeReplace.varMetadata",
 		"varTypeReplace.dfMetadata", "varTypeReplace.mframe",
		
	"varCoerce.default", "varCoerce.varMetadata", 
		"varCoerce.dfMetadata", "varCoerce.mframe", 
    "varCoerceReplace", "varCoerceReplace.default", 
		"varCoerceReplace.varMetadata", "varCoerceReplace.dfMetadata", 
		"varCoerceReplace.mframe",
		
	"naOk.default", "naOk.varMetadata", "naOk.dfMetadata", "naOk.mframe", 		
	"naOkReplace", "naOkReplace.default", "naOkReplace.varMetadata", 
		"naOkReplace.dfMetadata", "naOkReplace.mframe",
 		
	"varDefault.default", "varDefault.varMetadata", "varDefault.dfMetadata", 
		"varDefault.mframe", 		
	"varDefaultReplace", "varDefaultReplace.default", 
		"varDefaultReplace.varMetadata", "varDefaultReplace.dfMetadata", 
		"varDefaultReplace.mframe",

	"is.varMetadata", "as.varMetadata", "as.varMetadata.default",
		"as.list.varMetadata", "as.character.varMetadata",
		"print.varMetadata", "Replace3.varMetadata",
 		
	"is.dfMetadata", "as.dfMetadata", "as.dfMetadata.default",    	
		"as.dfMetadata.list", "as.dfMetadata.data.frame",
    	"as.dfMetadata.dfMetadata", "as.list.dfMetadata",
		"print.dfMetadata", "customAttrNames.dfMetadata", 
		"Extract2.dfMetadata", "Replace.dfMetadata",
		"allowNewColumns", "allowNewColumnsReplace.dfMetadata",
			
	"as.data.frame.dfMetadata", "as.data.frame.mframe",	
	"is.mframe", "as.mframe", "as.mframe.default",
		"print.mframe", "mframeReplace", "mframeReplace2",

	".VM_RESERVED_NAMES", "checkType", "doVarCoercion", "xpdrows.mframe",
	"customAttrNames.mframe"
);
 
unlink(file.path(devPath(), "man", paste(toRm, ".Rd", sep="")))

# 4) Check the package (normally through StatET)
# R CMD Check
